# -*- coding: UTF-8 -*-
"""
兼容入口：所有 HTML 生成逻辑已拆至 src.html 包。
保留本文件仅用于兼容 from src.module_html import xxx。
"""
from src.html import (
    get_top_navbar_html,
    get_sidebar_menu_items_html,
    get_legacy_sidebar_html,
    get_lyrics_script,
    get_css_style,
    get_javascript_code,
    enhance_fund_tab_content,
    get_table_html,
    generate_holdings_cards_html,
    generate_terminal_dashboard_html,
    get_full_page_html_sidebar,
    get_full_page_html,
    get_sse_loading_page,
    get_sidebar_navigation_html,
    get_header_bar_html,
    get_summary_bar_html,
    generate_fund_row_html,
    generate_holdings_section_html,
    generate_watchlist_section_html,
    get_market_page_html,
    get_news_page_html,
    get_admin_users_page_html,
    get_precious_metals_page_html,
    get_market_indices_page_html,
    get_portfolio_page_html,
    get_fund_group_page_html,
    get_market_icon,
    get_position_records_page_html,
    get_sectors_page_html,
)

__all__ = [
    'get_top_navbar_html',
    'get_sidebar_menu_items_html',
    'get_legacy_sidebar_html',
    'get_lyrics_script',
    'get_css_style',
    'get_javascript_code',
    'enhance_fund_tab_content',
    'get_table_html',
    'generate_holdings_cards_html',
    'generate_terminal_dashboard_html',
    'get_full_page_html_sidebar',
    'get_full_page_html',
    'get_sse_loading_page',
    'get_sidebar_navigation_html',
    'get_header_bar_html',
    'get_summary_bar_html',
    'generate_fund_row_html',
    'generate_holdings_section_html',
    'generate_watchlist_section_html',
    'get_market_page_html',
    'get_news_page_html',
    'get_admin_users_page_html',
    'get_precious_metals_page_html',
    'get_market_indices_page_html',
    'get_portfolio_page_html',
    'get_fund_group_page_html',
    'get_market_icon',
    'get_position_records_page_html',
    'get_sectors_page_html',
]
